hostname: rancheros

rancher:
  console: ubuntu
  network:
    dns:
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
    interfaces:
      eth0:
        dhcp: true
        
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDWxbHdeT7qdNRYBA8MVzrQDlzvgHLlPDe+JfV/Q3tQDvR3Bbmy57SoLKkEIFBljPtMvcqGT2BGHPI3/TJoejA7+PiCPCQImL94yjUCAF0DcQwkMpkkDSuSKIejnTo78muIIZHi/uk/wlXWr2VlLbQi/YQCYMBjVARNBaW6CGWfyKeIkdKFv6oSKrFEUP7Kb5SV36xM+uwA/X+CWMVPkFmejpv4tbJ5t4OvgmrqUoppDuI7nXz3+rQdjlMOyRbZUanUBLFqbaAlEU1HCWslfwl/T4aciZRVHGbuCt+6IhPvZjkThFgicgtItRjRMfrYLt5hCHrCP20OcMav3ng6KjsX5BF53Y/nc7xayO9OU/0jgEjmNPNO3gqFKpZ7mYEUkorB92d0+ATgRCpO9EU87MTajENEGoBnSR2rSYxEI60+ufSC1aSqFKeYADmk6YK9qismM0yEeDkRqfYFW5+R1z/KPJ3x6UQk/h/Y+QIrJTPghHEpOy7ok1VKtIOG00F+g6oxEv0m03OVwFqW8sxE6zThWk8o/gAUiJSq6eMQoaKgN3TXeubKaz+xqlkopHOZhB2UiSSajmTdETdB1NV9Gsrx/bqVrfaPON2qHoy69dtxybeQixUTuU5J2ETXiHZ1xLm4JluFFrs8Qs+P0/YFQC6RUW3FmJlugM/eNfm+UNV7kw== dezzy@HELLBEAST

runcmd:
  - apt update
  - apt -y install vim-gtk3

write_files:
  - path: /home/rancher/.vimrc
    permissions: "0644"
    owner: rancher
    content: |
      set number
      set linebreak
      set showbreak=+++
      set textwidth=100
      set showmatch 
      set visualbell
      set hlsearch
      set smartcase
      set ignorecase
      set incsearch
      set autoindent
      set expandtab
      set shiftwidth=2
      set smartindent
      set smarttab
      set softtabstop=2
      set ruler
      set undolevels=1000
      set backspace=indent,eol,start
    
