sendAnonymousUsage = false
debug = false
logLevel = "WARN"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mav.duckdns.org"
watch = true
exposedByDefault = false

[acme]
email = "matjaz.mav@gmail.com"
storage = "/var/opt/acme.json"
entryPoint = "https"
onHostRule = true
    [acme.dnsChallenge]
    provider = "duckdns"
    delayBeforeCheck = 0